"""empty message

Revision ID: 8350367705bc
Revises: f8303ec81067
Create Date: 2024-03-22 17:25:29.951255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8350367705bc'
down_revision: Union[str, None] = 'f8303ec81067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods_menu', sa.Column('is_have', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods_menu', 'is_have')
    # ### end Alembic commands ###
