"""empty message

Revision ID: a3596cbd1d37
Revises: 0fe92808d864
Create Date: 2024-03-23 22:05:09.820017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3596cbd1d37'
down_revision: Union[str, None] = '0fe92808d864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about_we', sa.Column('lang', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about_we', 'lang')
    # ### end Alembic commands ###
